// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlgelzbesidzukfvntku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZ2VsemJlc2lkenVrZnZudGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjYxNzMsImV4cCI6MjA2OTY0MjE3M30.hXbD7hpJ0QR_jqgQAhT-eQjzQz-N12ygYKga-PAzLzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});